version: '3.8'

services:
  db:
    container_name: db
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
  backend:
    container_name: backend
    build:
      context: .
      target: prod
      dockerfile: Dockerfile.backend
    ports:
      - "3000:3000"
  frontend:
    container_name: frontend
    build:
      context: .
      target: prod
      dockerfile: Dockerfile.frontend
    ports:
      - "8080:3000"
networks:
  default:
      name: ${NETWORK_NAME}